name: grepmail
version: 5.3033
abstract: search mailboxes for mail matching a regular expression
author: David Coppit <david@coppit.org>
license: gpl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.004
  Date::Parse: 0
  Mail::Mbox::MessageParser: 1.4001
recommends:
  Digest::MD5: 0
  Date::Manip: 0
  Benchmark::Timer: 0.7100
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
