# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         grepmail
version:      5.22
version_from: grepmail
installdirs:  site
requires:
    Date::Parse:                   0
    Mail::Mbox::MessageParser:     1.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
